@extends('layouts.app')
@section('content')
<div class="page-title"><div><h1>{{ __('ui.product_features') }}</h1><p>{{ __('ui.feature_catalog_help') }}</p></div><a class="primary button" href="{{ route('features.create') }}">+ {{ __('ui.new_feature') }}</a></div>
<div class="planning-notice"><x-icon name="box"/><div><strong>{{ __('ui.modular_phase_preparation') }}</strong><p>{{ __('ui.feature_planning_notice') }}</p></div></div>
<section class="panel">@php($searchScope = 'features')@include('admin.search')<div class="list-summary">{{ __('ui.result_count', ['count' => $rows->total()]) }}</div>
<div class="table-wrap"><table><thead><tr><th>{{ __('ui.name') }}</th><th>{{ __('ui.product') }}</th><th>{{ __('ui.category') }}</th><th>{{ __('ui.feature_policy') }}</th><th>{{ __('ui.status') }}</th><th>{{ __('ui.planned_licenses') }}</th><th>{{ __('ui.actions') }}</th></tr></thead><tbody>
@forelse($rows as $feature)<tr><td><strong>{{ $feature->name }}</strong><small class="table-subtext"><code dir="ltr">{{ $feature->key }}</code></small></td><td>{{ $feature->product?->name }}</td><td>{{ $feature->category ?: '—' }}</td><td><span class="badge {{ $feature->is_required ? 'published' : '' }}">{{ __($feature->is_required ? 'ui.required_feature' : 'ui.optional_feature') }}</span></td><td><span class="badge {{ $feature->active ? 'active' : 'inactive' }}">{{ __($feature->active ? 'ui.state_active' : 'ui.state_inactive') }}</span></td><td>{{ $feature->licenses_count }}</td><td><div class="actions"><a class="table-action" href="{{ route('features.edit',$feature) }}">{{ __('ui.edit') }}</a><form method="post" action="{{ route('features.destroy',$feature) }}">@csrf @method('DELETE')<button class="danger-button" data-confirm="{{ __('ui.confirm_delete_feature') }}">{{ __('ui.delete') }}</button></form></div></td></tr>@empty<tr><td colspan="7" class="empty">{{ __('ui.no_features') }} <a href="{{ route('features.create') }}">{{ __('ui.new_feature') }}</a></td></tr>@endforelse
</tbody></table></div>{{ $rows->links() }}</section>
@endsection
