<?php

use App\Http\Controllers\{AuthController,HealthController};
use App\Http\Controllers\Admin\{CustomerController,DashboardController,LicenseController,MonitoringController,ProductController,ReleaseController};
use Illuminate\Support\Facades\Route;
Route::get('/health',HealthController::class);
Route::get('/login',[AuthController::class,'loginForm'])->name('login');Route::post('/login',[AuthController::class,'login'])->middleware('throttle:6,1');Route::post('/logout',[AuthController::class,'logout'])->name('logout');Route::post('/locale/{locale}',[AuthController::class,'locale'])->name('locale');
Route::middleware(['auth','role:super_admin,admin,viewer'])->group(function(){Route::get('/',DashboardController::class)->name('dashboard');Route::get('/customers',[CustomerController::class,'index'])->name('customers.index');Route::get('/products',[ProductController::class,'index'])->name('products.index');Route::get('/releases',[ReleaseController::class,'index'])->name('releases.index');Route::get('/licenses',[LicenseController::class,'index'])->name('licenses.index');Route::get('/installations',[MonitoringController::class,'installations'])->name('installations.index');Route::get('/security-events',[MonitoringController::class,'security'])->name('security.index');Route::get('/audit-logs',[MonitoringController::class,'audit'])->name('audit.index');});
Route::middleware(['auth','role:super_admin,admin'])->group(function(){Route::get('/customers/create',[CustomerController::class,'create'])->name('customers.create');Route::post('/customers',[CustomerController::class,'store'])->name('customers.store');Route::get('/products/create',[ProductController::class,'create'])->name('products.create');Route::post('/products',[ProductController::class,'store'])->name('products.store');Route::get('/releases/create',[ReleaseController::class,'create'])->name('releases.create');Route::post('/releases',[ReleaseController::class,'store'])->name('releases.store');Route::get('/licenses/create',[LicenseController::class,'create'])->name('licenses.create');Route::post('/licenses',[LicenseController::class,'store'])->name('licenses.store');Route::post('/releases/{release}/publish',[ReleaseController::class,'publish'])->name('releases.publish');Route::post('/licenses/{license}/status/{status}',[LicenseController::class,'status'])->name('licenses.status');});
