<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration {
    public function up(): void {
        Schema::table('users', function (Blueprint $t) { $t->string('role')->default('viewer'); $t->string('locale', 5)->default('fa'); $t->boolean('active')->default(true); });
        Schema::create('customers', function (Blueprint $t) { $t->id(); $t->uuid('uuid')->unique(); $t->string('name'); $t->string('company_name')->nullable(); $t->string('email')->nullable()->index(); $t->string('phone')->nullable(); $t->text('notes')->nullable(); $t->string('status')->default('active')->index(); $t->timestamps(); $t->softDeletes(); });
        Schema::create('products', function (Blueprint $t) { $t->id(); $t->uuid('uuid')->unique(); $t->string('name'); $t->string('slug')->unique(); $t->text('description')->nullable(); $t->string('status')->default('active')->index(); $t->timestamps(); });
        Schema::create('releases', function (Blueprint $t) { $t->id(); $t->uuid('uuid')->unique(); $t->foreignId('product_id')->constrained(); $t->string('version'); $t->string('channel')->default('stable'); $t->string('status')->default('draft')->index(); $t->string('source_type')->default('manual'); $t->string('source_reference')->nullable(); $t->text('release_notes')->nullable(); $t->string('package_filename')->nullable(); $t->string('package_path')->nullable(); $t->unsignedBigInteger('package_size')->nullable(); $t->string('package_sha256',64)->nullable(); $t->string('git_commit')->nullable(); $t->timestamp('published_at')->nullable(); $t->timestamps(); $t->softDeletes(); $t->unique(['product_id','version','channel']); });
        Schema::create('licenses', function (Blueprint $t) { $t->id(); $t->uuid('uuid')->unique(); $t->string('license_key_hash',64)->unique(); $t->string('license_key_prefix',12)->index(); $t->foreignId('customer_id')->constrained(); $t->foreignId('product_id')->constrained(); $t->foreignId('release_id')->nullable()->constrained(); $t->string('status')->default('created')->index(); $t->unsignedInteger('max_installations')->default(1); $t->timestamp('expires_at')->nullable()->index(); $t->timestamp('activated_at')->nullable(); $t->foreignId('created_by')->nullable()->constrained('users')->nullOnDelete(); $t->json('metadata')->nullable(); $t->timestamps(); $t->softDeletes(); });
        Schema::create('installations', function (Blueprint $t) { $t->id(); $t->uuid('uuid')->unique(); $t->foreignId('license_id')->constrained(); $t->foreignId('customer_id')->constrained(); $t->foreignId('product_id')->constrained(); $t->foreignId('release_id')->nullable()->constrained(); $t->string('installation_token_hash',64)->unique(); $t->string('hostname'); $t->string('fingerprint',64)->index(); $t->unsignedSmallInteger('fingerprint_version')->default(1); $t->string('machine_id_hash',64)->nullable(); $t->string('product_uuid_hash',64)->nullable(); $t->string('board_serial_hash',64)->nullable(); $t->string('system_serial_hash',64)->nullable(); $t->string('disk_serial_hash',64)->nullable(); $t->string('cpu_model')->nullable(); $t->unsignedSmallInteger('cpu_cores')->nullable(); $t->unsignedBigInteger('ram_bytes')->nullable(); $t->unsignedBigInteger('disk_size_bytes')->nullable(); $t->string('os_name')->nullable(); $t->string('os_version')->nullable(); $t->string('kernel_version')->nullable(); $t->string('virtualization_type')->nullable(); $t->string('agent_version')->nullable(); $t->string('application_version')->nullable(); $t->ipAddress('first_ip')->nullable(); $t->ipAddress('last_ip')->nullable(); $t->timestamp('first_seen_at')->nullable(); $t->timestamp('last_seen_at')->nullable()->index(); $t->timestamp('activated_at')->nullable(); $t->timestamp('locked_at')->nullable(); $t->string('status')->default('active')->index(); $t->string('lock_reason')->nullable(); $t->foreignId('target_release_id')->nullable()->constrained('releases'); $t->json('health')->nullable(); $t->timestamps(); $t->softDeletes(); $t->unique(['license_id','fingerprint']); });
        Schema::create('license_leases', function (Blueprint $t) { $t->id(); $t->uuid('uuid')->unique(); $t->foreignId('installation_id')->constrained()->cascadeOnDelete(); $t->timestamp('issued_at'); $t->timestamp('expires_at')->index(); $t->json('payload'); $t->text('signature'); $t->timestamps(); });
        Schema::create('download_tokens', function (Blueprint $t) { $t->id(); $t->string('token_hash',64)->unique(); $t->foreignId('installation_id')->constrained()->cascadeOnDelete(); $t->foreignId('release_id')->constrained(); $t->timestamp('expires_at')->index(); $t->timestamp('used_at')->nullable(); $t->timestamps(); });
        Schema::create('request_nonces', function (Blueprint $t) { $t->id(); $t->foreignId('installation_id')->constrained()->cascadeOnDelete(); $t->string('nonce',128); $t->timestamp('expires_at')->index(); $t->timestamps(); $t->unique(['installation_id','nonce']); });
        Schema::create('security_events', function (Blueprint $t) { $t->id(); $t->uuid('uuid')->unique(); $t->string('type')->index(); $t->foreignId('license_id')->nullable()->constrained(); $t->foreignId('installation_id')->nullable()->constrained(); $t->ipAddress('ip_address')->nullable(); $t->string('request_id')->nullable()->index(); $t->json('context')->nullable(); $t->timestamp('occurred_at')->index(); $t->timestamps(); });
        Schema::create('audit_logs', function (Blueprint $t) { $t->id(); $t->uuid('uuid')->unique(); $t->foreignId('user_id')->nullable()->constrained()->nullOnDelete(); $t->string('action')->index(); $t->string('subject_type')->nullable(); $t->unsignedBigInteger('subject_id')->nullable(); $t->json('before')->nullable(); $t->json('after')->nullable(); $t->ipAddress('ip_address')->nullable(); $t->string('request_id')->nullable(); $t->timestamp('occurred_at')->index(); $t->timestamps(); $t->index(['subject_type','subject_id']); });
        Schema::create('settings', function (Blueprint $t) { $t->id(); $t->string('key')->unique(); $t->text('value')->nullable(); $t->boolean('encrypted')->default(false); $t->timestamps(); });
        Schema::create('repository_integrations', function (Blueprint $t) { $t->id(); $t->string('provider'); $t->string('repository_url'); $t->string('branch')->nullable(); $t->text('encrypted_access_token')->nullable(); $t->text('encrypted_webhook_secret')->nullable(); $t->boolean('enabled')->default(false); $t->timestamp('last_sync_at')->nullable(); $t->string('last_commit')->nullable(); $t->timestamps(); });
        Schema::create('installation_events', function (Blueprint $t) { $t->id(); $t->foreignId('installation_id')->constrained()->cascadeOnDelete(); $t->string('type')->index(); $t->json('context')->nullable(); $t->timestamp('occurred_at')->index(); $t->timestamps(); });
    }
    public function down(): void { foreach (['installation_events','repository_integrations','settings','audit_logs','security_events','request_nonces','download_tokens','license_leases','installations','licenses','releases','products','customers'] as $table) Schema::dropIfExists($table); Schema::table('users', fn(Blueprint $t) => $t->dropColumn(['role','locale','active'])); }
};
